### ISSUE TITLE
constant decorator will not work as desired if method's return value is None

### ISSUE THREAD

**Issue by chaburkland** [InvestmentSystems/class-only-design#8]
https://github.com/InvestmentSystems/class-only-design/blob/55895ad3a4668bb6fc64075ff4fecfebb2b3466f/class_only_design/api.py#L20

The constant wrapper does not work as expected if the return value of the wrapped method is `None`. I will create a PR shortly that fixes this edge case by implementing a sentinel object as the flag for whether or not the first call has been called or not.

Here is an example of the undesired behavior:
```
10:26:27  In [8] from time import sleep

10:26:29  In [9] class Foo: 
            ...:     @constant 
            ...:     def do_hard_work(cls): 
            ...:         sleep(5)
            ...:
            ...:     @classmethod 
            ...:     def api(cls): 
            ...:         cls.do_hard_work 
            ...:         return 12 
            ...:                                                                

10:26:32  In [10] Foo.api()  # Notice this will take 5 seconds
10:26:37 Out [10] 12

10:26:38  In [11] Foo.api()  # Notice this will also take 5 seconds
10:26:43 Out [11] 12
```

**Comment by ForeverWintr** [comment]
Thanks! That's a good edge case to consider, and I'm happy to accept a pull request implementing your fix. 

I'm curious though, do you have a situation where that edge case is relevant?

**Comment by chaburkland** [comment]
Not specifically. I was just reading through this repo since I was interested it, and that portion of code caught my eye.
